CREATE DATABASE IF NOT EXISTS `loja_db`;

USE `loja_db`;

CREATE TABLE IF NOT EXISTS `salesman` (
  `SALESMAN_ID` INT(5) NOT NULL,
  `NAME` VARCHAR(30) NOT NULL,
  `CITY` VARCHAR(15),
  `COMMISSION` DECIMAL(5,2),
  PRIMARY KEY (`SALESMAN_ID`)
);

CREATE TABLE IF NOT EXISTS `customer` (
  `CUSTOMER_ID` INT(5) NOT NULL,
  `CUST_NAME` VARCHAR(30) NOT NULL,
  `CITY` VARCHAR(15),
  `GRADE` INT(3),
  `SALESMAN_ID` INT(5),
  PRIMARY KEY (`CUSTOMER_ID`),
  FOREIGN KEY (`SALESMAN_ID`) REFERENCES `salesman`(`SALESMAN_ID`)
);

CREATE TABLE IF NOT EXISTS `orders` (
  `ORD_NO` INT(5) NOT NULL,
  `PURCH_AMT` DECIMAL(8,2) NOT NULL,
  `ORD_DATE` DATE NOT NULL,
  `CUSTOMER_ID` INT(5),
  `SALESMAN_ID` INT(5),
  PRIMARY KEY (`ORD_NO`),
  FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `customer`(`CUSTOMER_ID`),
  FOREIGN KEY (`SALESMAN_ID`) REFERENCES `salesman`(`SALESMAN_ID`)
);